"""empty message

Revision ID: 188dc4b0429c
Revises: 59fbc5d22e22
Create Date: 2016-11-20 21:38:03.456148

"""

# revision identifiers, used by Alembic.
revision = '188dc4b0429c'
down_revision = '59fbc5d22e22'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phase_element_answer', sa.Column('label', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phase_element_answer', 'label')
    ### end Alembic commands ###
