"""empty message

Revision ID: 1be01c56f145
Revises: 388ae1d13311
Create Date: 2016-11-23 18:53:41.241749

"""

# revision identifiers, used by Alembic.
revision = '1be01c56f145'
down_revision = '388ae1d13311'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('select_option', sa.Column('content_type', sa.String(length=1)))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('select_option', 'content_type')
    ### end Alembic commands ###
