"""empty message

Revision ID: 3224f2105752
Revises: 59fbc5d22e22
Create Date: 2016-11-22 20:45:14.288939

"""

# revision identifiers, used by Alembic.
revision = '3224f2105752'
down_revision = '59fbc5d22e22'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phase_element_duration_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('recording_data_id', sa.Integer(), nullable=True),
    sa.Column('phase_element_id', sa.Integer(), nullable=True),
    sa.Column('view_start', sa.DateTime(), nullable=False),
    sa.Column('view_end', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['phase_element_id'], ['phase_element.id'], ),
    sa.ForeignKeyConstraint(['recording_data_id'], ['experiment_recording_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phase_element_duration_data')
    ### end Alembic commands ###
