"""empty message

Revision ID: 388ae1d13311
Revises: 188dc4b0429c
Create Date: 2016-11-22 09:13:19.535838

"""

# revision identifiers, used by Alembic.
revision = '388ae1d13311'
down_revision = '188dc4b0429c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phase_element_answer', sa.Column('content_type', sa.String(length=2), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phase_element_answer', 'content_type')
    ### end Alembic commands ###
