"""empty message

Revision ID: 39ebb593377
Revises: 4cfa92003a48
Create Date: 2016-07-25 20:44:08.181818

"""

# revision identifiers, used by Alembic.
revision = '39ebb593377'
down_revision = '4cfa92003a48'

from alembic import op
import sqlalchemy as sa


def upgrade():
    with op.batch_alter_table('experiment') as batch_op:
        batch_op.drop_column('creation_date')


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column('creation_date', sa.DATETIME(), nullable=True))
    ### end Alembic commands ###
