"""empty message

Revision ID: 3f0321337a6a
Revises: 2f5f5b50ad2e
Create Date: 2016-10-25 23:53:53.919506

"""

# revision identifiers, used by Alembic.
revision = '3f0321337a6a'
down_revision = '2f5f5b50ad2e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_emotiv_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=1), nullable=False),
    sa.Column('recording_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recording_data_id'], ['experiment_recording_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiment_gaze_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('recording_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recording_data_id'], ['experiment_recording_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'experiment_recording_data', 'file_name')
    op.drop_column(u'experiment_recording_data', 'data_type')
    op.drop_column(u'phase_element_recording_data', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'phase_element_recording_data', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'phase_element_recording_data', 'user', ['user_id'], ['id'])
    op.add_column(u'experiment_recording_data', sa.Column('data_type', sa.VARCHAR(length=1), nullable=False))
    op.add_column(u'experiment_recording_data', sa.Column('file_name', sa.VARCHAR(length=255), nullable=False))
    op.drop_table('experiment_gaze_data')
    op.drop_table('experiment_emotiv_data')
    ### end Alembic commands ###
