"""empty message

Revision ID: 4da40a926884
Revises: 3b6be60904b0
Create Date: 2016-04-14 03:50:27.867491

"""

# revision identifiers, used by Alembic.
revision = '4da40a926884'
down_revision = '3b6be60904b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column('last_setup_step_completed', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment', 'last_setup_step_completed')
    ### end Alembic commands ###
