"""empty message

Revision ID: 59fbc5d22e22
Revises: 3f0321337a6a
Create Date: 2016-11-01 11:56:23.530753

"""

# revision identifiers, used by Alembic.
revision = '59fbc5d22e22'
down_revision = '3f0321337a6a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_recording_data', sa.Column('screen_height', sa.Integer(), nullable=True))
    op.add_column('experiment_recording_data', sa.Column('screen_width', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment_recording_data', 'screen_width')
    op.drop_column('experiment_recording_data', 'screen_height')
    ### end Alembic commands ###
